### ISSUE TITLE
As a developer I want a simples settings flow so that the user can manage its Offer decisions

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/client-library-android#105]
### User Story

As a developer I want a simples settings flow so that the user can manage its Offer decisions

### Description

The Settings screen simplifies user management of OptIn decisions. Here, users can review past decisions and make changes as needed. All license records are automatically updated based on user actions within the settings, including permission states.

This structured approach to OptIn offer management ensures transparency, compliance, and user control over data usage permissions.

### Acceptance Criteria

- [ ] #109
- [ ] User can optin in declined Offer
- [ ] User can optout in an accepted Offer
- [ ] The developer can set which Offer can be changed
- [ ] If a required permission is revoked the Offer is declined

### Tasks
- [x] #118 
- [x] #119 
- [x] #120 
- [x] #121 
- [x] #122
