### ISSUE TITLE
As a developer I want a simple predefined user flow so that the user can decide about an Offer

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/client-library-android#106]
### User Story

As a developer I want a simple predefined user flow so that the user can decide about an Offer

### Description

<img width="866" alt="Captura de Tela 2024-05-13 às 11 34 00" src="https://github.com/mytiki/client-library-ios/assets/8357343/d02ab472-a120-4935-a5df-af4e9cef22c3">

The Offer Flow outlines the sequential steps necessary for a successful OptIn process, ensuring compliance with privacy standards mandated by app stores. It consists of:

**Permissions Screen:** This initial screen is mandatory if device permissions are requested. It ensures compliance with app store regulations regarding protected device permissions. Users are prompted to grant necessary permissions based on presented use cases.

**Offer Screen:** Following permission grants (or if no permissions are required), the Offer Screen is displayed. Here, users are informed about the rewards for accepting the offer and how their data will be used. Users can accept or deny the offer at this stage.

User decisions are recorded in a License Record within the TIKI Licensing Infrastructure and can be modified later via the OptIn Settings screen.

### Acceptance Criteria

- [ ] The permissions screen is presented, if the user denies, the Offer is denied
- [ ] Android ask for the required permissions, if the user denies, the Offer is denied
- [ ] The offer screen is presented , if the user denies, the Offer is denied. Otherwise the offer is accepted

### Tasks
- [x] #117 
- [x] #110
