### ISSUE TITLE
As a developer I need to manage the offers and the user decisions about each so that it preciselly registered in TIKI trail

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/client-library-android#107]
### User Story

As a developer I need to manage the offers and the user decisions about each so that it preciselly registered in TIKI trail

### Description

The Offer service needs methods for:

- accept the Offer
- decline the Offer
- retrieve the user decision about an Offer
- change the user decision

### Acceptance Criteria

- [x] accepting an Offer creates a License and a Payable, based in the Offer
- [x] declining an Offer creates a License with the Offer PTR but without use cases/destinations
- [x] the user decisions about the offers can be retrieved from TIKI trail
- [x] the user can change the decision about a previously accepted or declined Offer can be
- [x] the developer can block which offers can change

### Tasks
- [x] #112 
- [x] #113 
- [x] #114 
- [x] #115 
- [x] #116
