### ISSUE TITLE
Publish PDF receipts

### ISSUE THREAD

**Issue by ricardobrg** [mytiki/client-library-android#87]
### Reason

Update the publish method to work with PDF receipts

### Description

Currently the publish method just accepts images for upload. Update this method to accept PDF files too.

It should change the parameters as follows, accepting:
- a single `Bitmap` 
- a list of `Bitmap` objects for multiple images
- a `File` representing a PDF, or 
- a list of `File` objects for multiple PDFs.

- [x] mytiki/client-library-android/issues/88
- [x] mytiki/client-library-android/issues/89
- [x] mytiki/client-library-android/issues/93
- [x] mytiki/client-library-android/issues/94
- [x] mytiki/client-library-android/issues/95
- [ ] publish

### Success Criteria

- [ ] the publish method works for all the inputs described
